
public class Main {
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		// Java program that demonstrates the use of throw
		class ThrowExcep
		{
			static void fun()
			{
				try
				{
					throw new NullPointerException("demo");
				}
				catch(NullPointerException e)
				{
					System.out.println("Caught inside fun().");
					throw e; // rethrowing the exception
				}
			}

			public static void main(String args[])
			{
				try
				{
					fun();
				}
				catch(NullPointerException e)
				{
					System.out.println("Caught in main.");
				}
			}
		}

	}

	/* (non-Java-doc)
	 * @see java.lang.Object#Object()
	 */
	public Main() {
		super();
	}

}